project:
  type: website

website:
  title: "Mesa Arrests in 2011-2019"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
        text: Model
      - href: source.qmd
        text: Sources
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



